### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by xioqing** [FrostMiKu/Share.CSS#2]
我用了你的css, 谢谢分享, trilium 分享的页面, 在手机上显示时左边会有菜单栏, 我想把它去掉不显示, 怎么更改? 谢谢

**Comment by FrostMiKu** [comment]
在css里把对应元素的display设置为none
如果需要仅在手机上不显示，你需要添加条件判断

--------------原始邮件--------------
发件人："xioqing ***@***.***&gt;;
发送时间：2023年10月8日(星期天) 凌晨5:38
收件人："FrostMiKu/Share.CSS" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[FrostMiKu/Share.CSS] 请教个问题 (Issue #2)
-----------------------------------

 

 
我用了你的css, 谢谢分享, trilium 分享的页面, 在手机上显示时左边会有菜单栏, 我想把它去掉不显示, 怎么更改? 谢谢

**Comment by xioqing** [comment]
> 在css里把对应元素的display设置为none 如果需要仅在手机上不显示，你需要添加条件判断
> […](#)
> --------------原始邮件-------------- 发件人："xioqing ***@***.***&gt;; 发送时间：2023年10月8日(星期天) 凌晨5:38 收件人："FrostMiKu/Share.CSS" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[FrostMiKu/Share.CSS] 请教个问题 (Issue #2) ----------------------------------- 我用了你的css, 谢谢分享, trilium 分享的页面, 在手机上显示时左边会有菜单栏, 我想把它去掉不显示, 怎么更改? 谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by xioqing** [comment]
> 在css裡把對應元素的顯示設定為none 如果只需要在手機上不顯示，則需要加入條件判斷
> [……](#)
> --------------原始邮件-------------- 发件人："xioqing ***@***.***&gt;; 发送时间：2023年10月8日(星期天) 凌晨5:38 收件人："FrostMiKu/Share.CSS" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[FrostMiKu/Share.CSS] 请教个问题 (Issue #2) ----------------------------------- 我用了你的css, 谢谢分享, trilium 分享的页面, 在手机上显示时左边会有菜单栏, 我想把它去掉不显示, 怎么更改? 谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢,  我找到关的地方了
